spring.application.name=foodies

#mongoDB configuration
spring.mongodb.uri=mongodb://localhost:27017/foodies

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-northeast-1
aws.s3.bucketName=foodies-foods-fd


jwt.secret.key=60c3f4be19333e3f47b4bcafe494187f165f63d7f489a7cc4febb3e3d9a4f54b
jwt.expiration=43200000

#Razorpay configuration
#razorpay_key=${RAZORPAY_KEY}
#rarorpay_secret_key=${RAZORPAY_SECRET_KEY}

sepay.bank.account: ${SEPAY_BANK_ACCOUNT}
sepay.bank.name: ${SEPAY_BANK_NAME}
sepay.webhook.secret: ${SEPAY_WEBHOOK_SECRET}
